Tweak profile.d loading

diff --git a/home/dot_dotrc.bash.tmpl b/home/dot_dotrc.bash.tmpl
--- a/home/dot_dotrc.bash.tmpl
+++ b/home/dot_dotrc.bash.tmpl
@@ -13,9 +13,10 @@ function PATH_add() {
     export PATH
 }
 
-find "{{ .path.home }}/.profile.d" -type f -name "*.bash" -o \! \( -name "*.*" \) |\
-    sort |\
-    while IFS= read -r f; do
-        # shellcheck disable=SC1090
-        source "$f" || echo "[{{ .path.home }}/.dotrc.bash] Failed to source $f" >&2
-    done
+if [ ! -f "$HOME/.profile.d.bash" ]; then
+    echo "Warning: ${HOME}/.profile.d.bash does not exist"
+    alias update="echo 'Error: ${HOME}/.profile.d.bash does not exist' >&2 && false"
+else
+    alias update="source ${HOME}/.profile.d.bash"
+    update
+fi
diff --git a/home/dot_dotrc.zsh.tmpl b/home/dot_dotrc.zsh.tmpl
--- a/home/dot_dotrc.zsh.tmpl
+++ b/home/dot_dotrc.zsh.tmpl
@@ -8,8 +8,10 @@ function PATH_add() {
     done
 }
 
-if [ ! -f .profile.d.all ]; then
-    echo "Warning: ${HOME}/.profile.d.all does not exist"
+if [ ! -f "$HOME/.profile.d.zsh" ]; then
+    echo "Warning: ${HOME}/.profile.d.zsh does not exist"
+    alias update="echo 'Error: ${HOME}/.profile.d.zsh does not exist' >&2 && false"
 else
-    . .profile.d.all
+    alias update="source ${HOME}/.profile.d.zsh"
+    source "${HOME}/.profile.d.zsh"
 fi
