more cleanup

diff --git a/home/dot_dotrc.tmpl b/home/dot_dotrc.tmpl
--- a/home/dot_dotrc.tmpl
+++ b/home/dot_dotrc.tmpl
@@ -1,37 +1,28 @@
 #!/usr/bin/env bash
 
-[ -z "$MWAY_FORCE_DOTRC" ] || { unset MWAY_DOTRC; unset MWAY_FORCE_DOTRC; }
+shopt -s autocd >/dev/null 2>&1
+shopt -s cdspell >/dev/null 2>&1
+shopt -s globstar >/dev/null 2>&1
+shopt -s nocaseglob >/dev/null 2>&1
 
-if [[ $MWAY_DOTRC -ne 1 ]]; then
-    export MWAY_DOTRC=1
-
-    shopt -s autocd 2>/dev/null
-    shopt -s cdspell 2>/dev/null
-    shopt -s globstar 2>/dev/null
-    shopt -s nocaseglob 2>/dev/null
-
-    # Well-known paths
-    export PATH="/usr/local/sbin:/usr/local/bin:$PATH"
-    _profiled_files="$(find {{ quote (print .paths.user.home "/.profile.d") }} -type f | sort)"
-
-    function PATH_add() {
-        for dir in "$@"; do
-            [ -z "$dir" ] || PATH="$dir${PATH:+:${PATH}}"
-        done
-
-        # https://stackoverflow.com/a/44232192
-        PATH="$(perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, $ENV{PATH}))')"
-
-        export PATH
-    }
-
-    for f in $_profiled_files; do
-        # shellcheck source=/dev/null
-        source "$f" || echo "[{{ print .paths.user.home "/.dotrc" }}] Failed to source $f"
+function PATH_add() {
+    for path in "$@"; do
+        [ -z "$path" ] || [[ ":$PATH:" == *":$path:"* ]] || PATH="$path:$PATH"
     done
 
-    # Give {{ .paths.local.bin }} and {{ .paths.user.bin }} precedence.
-    PATH_add {{ quote .paths.local.bin }} {{ quote .paths.user.bin }}
+    export PATH
+}
 
-    set +e
-fi
+function source_if_exists() {
+    # shellcheck disable=SC1090
+    [ -z "$1" ] || [ ! -f "$1" ] || source "$1"
+}
+
+# Managed by chezmoi
+export PATH="{{ .path.path }}"
+
+_profiled_files="$(find "{{ .path.home }}/.profile.d" -type f | sort)"
+for f in $_profiled_files; do
+    # shellcheck disable=SC1090
+    source "$f" || echo "[{{ .path.home }}/.dotrc] Failed to source $f" >&2
+done
