chore: Misc cleanup, Python tweaks

diff --git a/home/.chezmoiscripts/run_after_12_pip.sh.tmpl b/home/.chezmoiscripts/run_after_12_pip.sh.tmpl
--- a/home/.chezmoiscripts/run_after_12_pip.sh.tmpl
+++ b/home/.chezmoiscripts/run_after_12_pip.sh.tmpl
@@ -1,12 +1,21 @@
 #!/usr/bin/env bash
 
-if which uv >/dev/null 2>&1; then
-  echo "$(ansi --white-intense --faint uv pip) installing (${HOME}/.requirements.txt)"
-  uv pip install --system -Uqr "${HOME}/.requirements.txt"
-elif which python3 >/dev/null 2>&1; then
-  echo "$(ansi --white-intense --faint pip) installing (${HOME}/.requirements.txt)"
-  python3 -m pip install -Uqr "${HOME}/.requirements.txt"
-else
-  echo "$(ansi --red-intense pip) cannot install without uv or python3"
-  exit 1
-fi
+_main() {
+  local venv="${HOME}/.local/share/uv/venv"
+
+  if which uv >/dev/null 2>&1; then
+    echo "$(ansi --white-intense --faint --bold uv pip) installing (${HOME}/.requirements.txt)"
+    uv venv -q --allow-existing "${venv}"
+    uv pip install --python "${venv}" -Uqr "${HOME}/.requirements.txt"
+  elif which python3 >/dev/null 2>&1; then
+    echo "$(ansi --white-intense --faint --bold pip) installing (${HOME}/.requirements.txt)"
+    [[ -d "${venv}/bin" ]] || python3 -m venv "${venv}"
+    source "${venv}/bin/activate"
+    python3 -m pip install -Uqr "${HOME}/.requirements.txt"
+  else
+    echo "$(ansi --red-intense --bold pip) cannot install without uv or python3"
+    exit 1
+  fi
+}
+
+_main "$@"
