Bootstrap ensure from release asset

diff --git a/home/dot_profile.d/20_aliases.tmpl b/home/dot_profile.d/20_aliases.tmpl
--- a/home/dot_profile.d/20_aliases.tmpl
+++ b/home/dot_profile.d/20_aliases.tmpl
@@ -7,7 +7,7 @@ BTOP_VERSION="${MW_BTOP_VERSION:-"1.3.1"}"
 CHEZMOI_VERSION="${MW_CHEZMOI_VERSION:-"2.46.1"}"
 DIFFTASTIC_VERSION="${MW_DIFFTASTIC_VERSION:-"0.54.0"}"
 DIRENV_VERSION="${MW_DIRENV_VERSION:-"2.33.0"}"
-ENSURE_VERSION="${MW_ENSURE_VERSION:-"0.3.6"}"
+ENSURE_VERSION="${MW_ENSURE_VERSION:-"0.4.0"}"
 EZA_VERSION="${MW_EZA_VERSION:-"0.17.0"}"
 FD_VERSION="${MW_FD_VERSION:-"9.0.0"}"
 FZF_VERSION="${MW_FZF_VERSION:-"0.46.0"}"
@@ -26,26 +26,71 @@ YQ_VERSION="${MW_YQ_VERSION:-"4.40.5"}"
 ZELLIJ_VERSION="${MW_ZELLIJ_VERSION:-"0.39.2"}"
 
 __ensure_path() {
-  which -as ensure | \grep -E '^/' | cut -d' ' -f1
+  which -as ensure | \grep -E '^/' | \cut -d' ' -f1
+}
+
+__get_latest_ensure_release_asset_url() {
+  readonly arch="$(uname -m)"
+  readonly os="$(uname -o | tr '[:upper:]' '[:lower:]')"
+
+  if command -v jq >/dev/null; then
+    \curl -sL \
+          -H "Authorization: Bearer ${MW_GITHUB_TOKEN}" \
+          https://api.github.com/repos/mway/ensure-go/releases | \
+      \jq ".[0].assets.[] | select(.name==\"ensure-${arch}-${os}\").url" | \
+      xargs
+  else
+    \curl -sL \
+          -H "Authorization: Bearer ${MW_GITHUB_TOKEN}" \
+          https://api.github.com/repos/mway/ensure-go/releases | \
+      \grep ensure-arm64-darwin -B 3 | \
+      \grep '"url"' | \
+      \head -n1 | \
+      \cut -d, -f1 | \
+      \awk '{print $NF}' | \
+      xargs
+  fi
 }
 
 __install_ensure() {
-  \go install "go.mway.dev/ensure@v${ENSURE_VERSION}"
+  readonly dst="$1"
+  local src;
+  src="$(__get_latest_ensure_release_asset_url)"
+
+  mkdir -p "$(dirname "$dst")" || {
+    echo "Error: failed to mkdir -p '$dst'"
+    return 1
+  }
+
+  \curl -sL \
+        -H "Authorization: Bearer ${MW_GITHUB_TOKEN}" \
+        -H 'Accept: application/octet-stream' \
+        -o "$dst" \
+        "${src}" || {
+    echo "Error: failed to fetch remote asset: ${src}"
+    return 1
+  }
+
+  chmod +x "$dst"
 }
 
 ensure() {
-  __ensure_path &>/dev/null || __install_ensure
-
-  local prog;
-  prog="$(__ensure_path)"
-  if [ -z "$prog" ]; then
+  local prog="$(__ensure_path)"
+  [ -n "$prog" ] || {
     echo "Ensure not found, installing..."
-    __install_ensure
-  fi
+    prog="$HOME/go/bin/ensure"
+    __install_ensure "$prog" || {
+      echo "Error: ensure ($prog) could not be installed"
+      return 1
+    }
+  }
 
   "$prog" --version 2>&1 | \grep "v${ENSURE_VERSION}" >/dev/null || {
-    echo "Updating ensure..."
-    __install_ensure
+    echo -n "Updating ensure..."
+    __install_ensure "$prog" || {
+      echo "Error: ensure ($prog) could not be installed"
+      return 1
+    }
   }
 
   local debug;
